name: Sync to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  sync-to-hf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git remote add space https://nupers:$HF_TOKEN@huggingface.co/spaces/nupers/crop
          git push space main --force
